### ISSUE TITLE
update

### ISSUE THREAD

**Issue by DimonYoing** [LBWBDeveloper/ChatGames-PM4#2]
Fix problems, not working properly

**Comment by TheRealDeveloper** [comment]
How Do you meen Not Working??
If your Server Crash then it is because you NEED EconomyAPI anyways it will Crash#
Or if you have an other Economy Plugin then Tell me Wich and if you have a OWN then add me on Discord and we are gonna do this!!!
LBWB#4773

**Comment by TheRealDeveloper** [comment]
I found the Bug, i will Fix it now!
Thanks for you Issue
!!!!!!!!!!

**Comment by TheRealDeveloper** [comment]
https://poggit.pmmp.io/ci/LBWBDeveloper/ChatGames-PM4/ChatGames-LBWB
